FROM node:18.1-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./ui/package.json ./

COPY ./ui/package-lock.json ./

RUN npm install

# Copy existing application directory contents
COPY ./ui ./

# RUN chown -R node:node 

# Copy existing application directory permissions
COPY --chown=node:node ./ui /app

EXPOSE 3000

CMD ["npm", "start"]